//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.05 at 03:59:09 PM CET 
//


package nl.hanze.web.rdw.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Info complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Info">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="statusInfoAanvraag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="voertuig" type="{http://service.rdw.web.hanze.nl/}Voertuig" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Info", propOrder = {
    "statusInfoAanvraag",
    "voertuig"
})
public class Info {

    @XmlElement(required = true)
    protected String statusInfoAanvraag;
    protected Voertuig voertuig;

    /**
     * Gets the value of the statusInfoAanvraag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusInfoAanvraag() {
        return statusInfoAanvraag;
    }

    /**
     * Sets the value of the statusInfoAanvraag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusInfoAanvraag(String value) {
        this.statusInfoAanvraag = value;
    }

    /**
     * Gets the value of the voertuig property.
     * 
     * @return
     *     possible object is
     *     {@link Voertuig }
     *     
     */
    public Voertuig getVoertuig() {
        return voertuig;
    }

    /**
     * Sets the value of the voertuig property.
     * 
     * @param value
     *     allowed object is
     *     {@link Voertuig }
     *     
     */
    public void setVoertuig(Voertuig value) {
        this.voertuig = value;
    }

}
