//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.05 at 03:59:09 PM CET 
//


package nl.hanze.web.rdw.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Voertuig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Voertuig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bsn" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="chassisNummer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="kenteken" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="kleur" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="model" type="{http://service.rdw.web.hanze.nl/}Model" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Voertuig", propOrder = {
    "bsn",
    "chassisNummer",
    "kenteken",
    "kleur",
    "model"
})
public class Voertuig {

    protected long bsn;
    protected String chassisNummer;
    protected String kenteken;
    protected String kleur;
    protected Model model;

    /**
     * Gets the value of the bsn property.
     * 
     */
    public long getBsn() {
        return bsn;
    }

    /**
     * Sets the value of the bsn property.
     * 
     */
    public void setBsn(long value) {
        this.bsn = value;
    }

    /**
     * Gets the value of the chassisNummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChassisNummer() {
        return chassisNummer;
    }

    /**
     * Sets the value of the chassisNummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChassisNummer(String value) {
        this.chassisNummer = value;
    }

    /**
     * Gets the value of the kenteken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKenteken() {
        return kenteken;
    }

    /**
     * Sets the value of the kenteken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKenteken(String value) {
        this.kenteken = value;
    }

    /**
     * Gets the value of the kleur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKleur() {
        return kleur;
    }

    /**
     * Sets the value of the kleur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKleur(String value) {
        this.kleur = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link Model }
     *     
     */
    public Model getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link Model }
     *     
     */
    public void setModel(Model value) {
        this.model = value;
    }

}
